# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70433dff070167296828bbcfe22f39083fd5f9125574268e8ee11333bca34eae94f3a34e0ecb25e6a3a2f43c166d0b57b6fb0a393021a1c2d0e9ef69d0c3f737

test:
  secret_key_base: 42763927f06c8cf41942a630d041d82fa176d6df970a7041e2c97c383299505bc733264492347fe70ed0ef1e614203879aa229955f14ae0758ce002bb0fb7ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
